views:
  - title: Home
    cards:
      - type: entities
        entities:
          - entity: switch.vtr300b_low_mode
            icon: mdi:fan-speed-1
          - entity: switch.vtr300b_normal_mode
            icon: mdi:fan-speed-2
          - entity: switch.vtr300b_high_mode
            icon: mdi:fan-speed-3
      - type: entities
        entities:
          - input_number.vtr300b_temperature
      - type: entities
        entities:
          - entity: sensor.vtr300b_reg_hc_temp_sp
            name: Temperature set point
          - entity: sensor.vtr300b_model_number
          - entity: sensor.vtr300b_ziema_vasara
          - entity: sensor.vtr300b_reg_rh_sensor_value
            name: Humidity
          - entity: sensor.vtr300b_reg_filter_days
            name: Days after last filter change
          - entity: sensor.vtr300b_reg_hc_temp_in5
            name: Outdoor air sensor
          - entity: sensor.vtr300b_reg_hc_temp_in1
            name: Supply air sensor
          - entity: sensor.vtr300b_reg_hc_temp_in2
            name: Extract air sensor
          - entity: sensor.vtr300b_reg_fan_sf_rpm
            name: Supply fan RPMs
            secondary_info: none
          - entity: sensor.vtr300b_reg_fan_ef_rpm
            name: Extract fan RPMs
          - entity: sensor.vtr300b_heater_type
          - entity: sensor.vtr300b_cooler_type
          - entity: sensor.vtr300b_main_version
          - entity: sensor.vtr300b_boot_version
      - type: entities
        entities:
          - entity: binary_sensor.vtr300b_filter_alarm
            name: Filter alarm
          - entity: binary_sensor.vtr300b_fan_alarm
            name: Fan Alarm
          - entity: binary_sensor.vtr300b_rotor_alarm
            name: Rotor alarm
          - entity: binary_sensor.vtr300b_frost_alarm
            name: Frost alarm
          - entity: binary_sensor.vtr300b_pcu_pb_alarm
            name: Pcu-pb alarm
          - entity: binary_sensor.vtr300b_emergency_thermostat_alarm
            name: Emergency thermostat alarm
          - entity: binary_sensor.vtr300b_damper_alarm
            name: Damper alarm
          - entity: binary_sensor.vtr300b_low_ss_alarm
            name: Low supply air temperature alarm
          - entity: binary_sensor.vtr300b_supply_air_sensor_alarm
            name: Supply air sensor alarm
          - entity: binary_sensor.vtr300b_defrost_alarm
            name: Defrost alarm
          - entity: binary_sensor.vtr300b_rh_sensor_alarm
            name: Humidity sensor alarm
